config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts do
    collection do
      get 'ranking'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
    self.data = [
        { id: 1, name: '---' },
        { id: 2, name: '趣味' },
        { id: 3, name: '雑談' },
        { id: 4, name: 'プログラミング' },
        { id: 5, name: 'テストメッセージ' }
    ]

    include ActiveHash::Associations
    has_many :posts
end

app/models/count.rb
class Count < ApplicationRecord
    belongs_to :post
end

app/models/month.rb
class Month < ActiveHash::Base
    self.data = [
        { id: 1, name: '---' },
        { id: 2, name: '1月' },
        { id: 3, name: '2月' },
        { id: 4, name: '3月' },
        { id: 5, name: '4月' },
        { id: 6, name: '5月' },
        { id: 7, name: '6月' },
        { id: 8, name: '7月' },
        { id: 9, name: '8月' },
        { id: 10, name: '9月' },
        { id: 11, name: '10月' },
        { id: 12, name: '11月' },
        { id: 13, name: '12月' }
    ]

    include ActiveHash::Associations
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord

    has_one_attached :image
    belongs_to :user
    has_one :count, dependent: :destroy

    validates :image, presence: true
    validates :title, presence: true
    validates :subtitle, presence: true
    validates :content, presence: true
    validates :category_id, numericality: { other_than: 1 }
    validates :month_id, numericality: { other_than: 1 }

    def self.ranking
        joins(:count).order('counts.count Desc')
    end

    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :category
    belongs_to :month
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitter_parameters, if: :devise_controller?
    before_action :basic_auth, if: :devise_sign_up?

    private
    def configure_permitter_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :position])        
    end

    def basic_auth
        authenticate_or_request_with_http_basic do |username, password|
        username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
        end
    end

    def devise_sign_up?
        controller_name == 'registrations' && action_name == 'new'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:edit, :show, :update]
    before_action :move_to_index, except: [:index, :show, :ranking]
    def index
        @posts = Post.includes(:user).order("created_at DESC")
    end

    def new
        @post = Post.new   
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            count_build(@post)
            redirect_to root_path           
        else
            render :new, status: :unprocessable_entity      
        end        
    end

    def show
        update_view_count(@post)
    end

    def edit     
    end

    def update
        if @post.update(post_params)
            redirect_to post_path(@post.id)            
        else
            render :edit, status: :unprocessable_entity
        end        
    end

    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to root_path
    end

    def ranking
        @posts = Post.ranking
        
    end

    private
    def post_params
        params.require(:post).permit(:title, :subtitle, :content, :image, :category_id, :month_id).merge(user_id: current_user.id)
    end

    def update_view_count(post)
        count = post.count || post.build_count
        count.increment!(:count)
        #integer型の保有制限は2147483647なので、のちに超過分を別カラムに記録する処理を考える 
    end

    def count_build(post)
        @count = Count.new(post_id: post.id)
        @count.save
    end

    def set_post
        @post = Post.find(params[:id])        
    end

    def move_to_index
        unless user_signed_in?
            redirect_to root_path            
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DialyDude</title>
    <link rel="icon" type="image/png" href="<%= asset_path('icon-bear.png') %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top pd-4">
    <%#= <a class="navbar-brand text-white" href="#">ロゴ</a> %>
    <%= link_to image_tag("bear.png"), root_path, class: "navbar-brand" %>

    <!-- ナビゲーションバーのトグルボタン -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- ナビゲーションバーのリンクとプルダウンリスト -->
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <%= link_to 'ホーム', root_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="#">カテゴリー(工事中)</a>
        </li>
        <li>
            <%= link_to 'ランキング', ranking_posts_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            その他メニュー
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">閲覧数(工事中)</a>
            <a class="dropdown-item" href="#">その他(工事中)</a>
            <div class="dropdown-divider"></div>
            <% if user_signed_in? %>
                <%= link_to 'サインアウト', destroy_user_session_path, data: { turbo_method: :delete}, class: 'dropdown-item' %>
                <%= link_to '新規投稿', new_post_path, class: 'dropdown-item' %>
            <% else %>
                <%= link_to '管理者ページ', new_user_session_path, class: 'dropdown-item' %>
            <% end %>
            </div>
        </li>
        </ul>
    </div>
    </nav>

    <%= yield %>

    <footer class="footer bg-dark text-light text-center py-3 mt-4">
        <div class="container">
            <p>&copy; 2023 DailyDude </p>
            <p>連絡先: あとで設定します（工事中）</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
    <div class="form-group">
        <%= form.label :title, 'タイトル',  class: 'form-label m-3' %>
        <%= form.text_field :title, class: 'form-control custom-width m-3' %>
    </div>

        <div class="form-group">
        <%= form.label :subtitle, 'サブタイトル',  class: 'form-label m-3' %>
        <%= form.text_field :subtitle, class: 'form-control custom-width m-3' %>
    </div>

    <div class="form-group">
        <%= form.label :content, '本文', class: 'form-label m-3' %>
        <%= form.text_area :content, class: 'form-control custom-width m-3', rows: 4 %>
    </div>

    <div class="form-group">
        <%= form.label :image, '画像', class: 'form-label m-3' %>
        <%= form.file_field :image, class: 'form-control custom-width m-3'%>
    </div>

    <div class="form-group">
        <%= form.label :category,'カテゴリー選択', class: "form-label" %>
        <%= form.collection_select :category_id, Category.all, :id, :name, {}, class: "form-control custom-width" %>
        </div>

        <div class="form-group">
        <%= form.label :month,'投稿月', class: "form-label" %>
        <%= form.collection_select :month_id, Month.all, :id, :name, {}, class: "form-control custom-width" %>
        </div>

    <div class="form-group">
        <%= form.submit '送信', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/posts/_top.html.erb
<div class="container mt-4">
    <div class="row">
    <% posts.each do |post| %>
        <div class="col-md-4 mb-10">
        <%= link_to post_path(post.id) do %>
        <div class="card">
            <%= image_tag post.image.variant(resize: '500x500'), class: 'card-img-top underline-punish' %>
            <div class="card-body">
            <h5 class="card-title"><%= post.title %></h5>
            <p class="card-text"><%= post.content %></p>
            </div>
        </div>
        <% end %>
        </div>
    <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<%= render partial: "form", locals: { post: @post } %>

app/views/posts/index.html.erb
<div class="container mt-4">
    <div class="row">
    <% @posts.each do |post| %>
        <div class="col-md-4 mb-10">
        <%= link_to post_path(post.id) do %>
        <div class="card">
            <%= image_tag post.image, class: 'card-img-top underline-punish custom-image-size' %>
            <div class="card-body">
            <h5 class="card-title"><%= post.title %></h5>
            <p class="card-text"><%= post.subtitle %></p>
            </div>
        </div>
        <% end %>
        </div>
    <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title, 'タイトル',  class: 'form-label m-3' %>
    <%= form.text_field :title, class: 'form-control custom-width m-3' %>
  </div>

    <div class="form-group">
    <%= form.label :subtitle, 'サブタイトル',  class: 'form-label m-3' %>
    <%= form.text_field :subtitle, class: 'form-control custom-width m-3' %>
  </div>

  <div class="form-group">
    <%= form.label :content, '本文', class: 'form-label m-3' %>
    <%= form.text_area :content, class: 'form-control custom-width m-3', rows: 4 %>
  </div>

  <div class="form-group">
    <%= form.label :image, '画像', class: 'form-label m-3' %>
    <%= form.file_field :image, class: 'form-control custom-width m-3'%>
  </div>

  <div class="form-group">
      <%= form.label :category,'カテゴリー選択', class: "form-label" %>
      <%= form.collection_select :category_id, Category.all, :id, :name, {}, class: "form-control custom-width" %>
    </div>

    <div class="form-group">
      <%= form.label :month,'投稿月', class: "form-label" %>
      <%= form.collection_select :month_id, Month.all, :id, :name, {}, class: "form-control custom-width" %>
    </div>

  <div class="form-group">
    <%= form.submit '送信', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/ranking.html.erb
<div class="container mt-4">
    <h1 class="text-center mb-4">閲覧数ランキング</h1>
    <div class="row">
        <% @posts.each_with_index do |post, index| %>
            <div class="col-md-4 mb-4">
                <div class="card">
                    <%= image_tag post.image, class: 'card-img-top underline-punish custom-image-size' %>
                    <div class="card-body">
                        <span class="badge bg-primary">第<%= index + 1 %>位</span>
                        <h5 class="card-title"><%= post.title %></h5>
                        <p class="card-text"><%= post.content %></p>
                        <p class="card-text"><strong>閲覧数:</strong> <%= post.count.count %> 回</p>
                        <%= link_to post_path(post.id), class: 'btn btn-info' do %>
                            詳細ページはこちらから！
                        <% end %>
                    </div>
                </div>
            </div>
            <% if index == 10 %>
                <% break %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-5">
    <!-- タイトル -->
    <h1 class="mb-4"><%= @post.title %></h1>

    <!-- 画像 -->
    <% if @post.image.attached? %>
    <div class="text-center mb-4">
        <%= image_tag @post.image, class: "img-fluid rounded image-width" %>
    </div>
    <% end %>

    <!-- サブタイトル -->
    <h2 class="mb-3"><%= @post.subtitle %></h2>

    <!-- 本文（枠線で囲む） -->
    <div class="border p-3 mb-4">
    <p><%= @post.content %></p>
    </div>



    <p>カテゴリー: <%= @post.category.name %></p>
    <p>投稿月: <%= @post.month.name %></p>

    <!-- 他の詳細情報の表示 -->

    <p>投稿日時<%= @post.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
    <p>閲覧数: <%= @post.count&.count || 0 %></p>

    <% if user_signed_in? %>
    <!-- 編集ボタン -->
    <%= link_to "編集", edit_post_path(@post), class: "btn btn-primary mr-5 mb-4" %>

    <!-- 削除ボタン -->
    <%= link_to "削除", post_path(@post), data: { turbo_method: :delete, confirm: "削除してもよろしいですか？" }, class: "btn btn-danger mr-5 mb-4" %>

    <% end %>
    
    <%= link_to "トップページに戻る", root_path, class: "btn btn-secondary mb-4" %>
</div>